services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - laravel

  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    command: ["php-fpm", "-F"]
    depends_on:
      - redis
    networks:
      - laravel

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
